<a href="https://colab.research.google.com/github/mazg-95/text-mining-image-processing/blob/main/Lab2_21000546.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Lab 2 - Digit Recognizer

Marco Zuñiga

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [13]:
from sklearn.metrics import accuracy_score

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [77]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPool2D, Flatten, Dropout

In [16]:
from tensorflow.keras import layers
from tensorflow.keras import initializers

In [8]:
path = '/content/drive/MyDrive/Cursos/Data Science/Ciclo3/Text Mining and Image Processing/Lab2/train.csv'
df = pd.read_csv(path)
df.head()

label  pixel0  pixel1  pixel2  ...  pixel780  pixel781  pixel782  pixel783
0      1       0       0       0  ...         0         0         0         0
1      0       0       0       0  ...         0         0         0         0
2      1       0       0       0  ...         0         0         0         0
3      4       0       0       0  ...         0         0         0         0
4      0       0       0       0  ...         0         0         0         0

[5 rows x 785 columns]

In [9]:
from sklearn.model_selection import train_test_split

X = df.iloc[:, 1:].values
y = df.iloc[:, 0]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=5)

In [10]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)

In [12]:
X_train.shape

(29400, 784)

### ANN

In [18]:
#ANN
ann = Sequential()

#capa de entrada
ann.add(Dense(input_dim=784, units=3000, activation='relu', kernel_initializer=initializers.GlorotUniform()))

#primera capa oculta
ann.add(Dense(units=1000, activation='relu', kernel_initializer=initializers.GlorotUniform()))

#capa de salida
ann.add(Dense(units=10, activation='softmax'))

In [19]:
ann.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [20]:
ann.fit(X_train, y_train, epochs=10, batch_size=64)

Epoch 1/10
460/460 [==============================] - 27s 56ms/step - loss: 0.3232 - accuracy: 0.9146
Epoch 2/10
460/460 [==============================] - 26s 57ms/step - loss: 0.1331 - accuracy: 0.9625
Epoch 3/10
460/460 [==============================] - 27s 59ms/step - loss: 0.1233 - accuracy: 0.9673
Epoch 4/10
460/460 [==============================] - 26s 57ms/step - loss: 0.0763 - accuracy: 0.9783
Epoch 5/10
460/460 [==============================] - 26s 56ms/step - loss: 0.0864 - accuracy: 0.9780
Epoch 6/10
460/460 [==============================] - 26s 56ms/step - loss: 0.0825 - accuracy: 0.9792
Epoch 7/10
460/460 [==============================] - 26s 57ms/step - loss: 0.0474 - accuracy: 0.9872
Epoch 8/10
460/460 [==============================] - 26s 57ms/step - loss: 0.0473 - accuracy: 0.9876
Epoch 9/10
460/460 [==============================] - 26s 57ms/step - loss: 0.0539 - accuracy: 0.9872
Epoch 10/10
460/460 [==============================] - 26s 57ms/step - loss: 0.040

In [21]:
ann.save('/content/drive/MyDrive/Cursos/Data Science/Ciclo3/Text Mining and Image Processing/Lab2/ann.h5')

In [22]:
ann_predicts = ann.predict(X_test)

In [23]:
ann_predict_vals = np.argmax(ann_predicts, axis=1)
ann_predict_vals

array([3, 5, 1, ..., 2, 6, 6])

In [93]:
ac_ann = accuracy_score(y_test.values, ann_predict_vals)
ac_ann

0.8797619047619047

### CNN

In [38]:
#Preparación de Data para CNN
X_train_cnn = np.reshape(X_train, (X_train.shape[0], 28,28,1))
X_test_cnn = np.reshape(X_test, (X_test.shape[0], 28,28,1))

In [40]:
X_train_cnn.shape

(29400, 28, 28, 1)

In [39]:
cnn = Sequential()

#----------------- fase de convolución -----------------

#primera capa de convoluciones
cnn.add(Conv2D(filters=64, kernel_size=(3,3), input_shape=(28, 28, 1), activation='relu'))

#capa de Max-Pooling
cnn.add(MaxPool2D(pool_size=(2,2)))

#segunda capa de convoluciones
cnn.add(Conv2D(filters=32, kernel_size=(3,3), activation='relu'))

#capa de Max-Pooling
cnn.add(MaxPool2D(pool_size=(2,2)))

#capa flatten
cnn.add(Flatten())

#----------------- fase de prediccion -----------------

#primera capa oculta.
cnn.add(Dense(units=128, activation='relu', kernel_initializer=initializers.GlorotUniform()))

#capa de salida
cnn.add(Dense(units=10, activation='softmax', kernel_initializer=initializers.GlorotUniform()))

In [41]:
cnn.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [42]:
cnn.fit(X_train_cnn, y_train, epochs=10, batch_size=64)

Epoch 1/10
460/460 [==============================] - 34s 72ms/step - loss: 0.2408 - accuracy: 0.9276
Epoch 2/10
460/460 [==============================] - 33s 72ms/step - loss: 0.0653 - accuracy: 0.9805
Epoch 3/10
460/460 [==============================] - 34s 74ms/step - loss: 0.0442 - accuracy: 0.9863
Epoch 4/10
460/460 [==============================] - 32s 70ms/step - loss: 0.0338 - accuracy: 0.9885
Epoch 5/10
460/460 [==============================] - 32s 71ms/step - loss: 0.0247 - accuracy: 0.9922
Epoch 6/10
460/460 [==============================] - 32s 70ms/step - loss: 0.0202 - accuracy: 0.9937
Epoch 7/10
460/460 [==============================] - 33s 72ms/step - loss: 0.0152 - accuracy: 0.9949
Epoch 8/10
460/460 [==============================] - 33s 71ms/step - loss: 0.0125 - accuracy: 0.9956
Epoch 9/10
460/460 [==============================] - 32s 69ms/step - loss: 0.0133 - accuracy: 0.9958
Epoch 10/10
460/460 [==============================] - 33s 71ms/step - loss: 0.007

In [44]:
cnn.save('/content/drive/MyDrive/Cursos/Data Science/Ciclo3/Text Mining and Image Processing/Lab2/cnn.h5')

In [112]:
predicts = cnn.predict(X_test_cnn)

In [113]:
predict_val = np.argmax(predicts, axis=1)
predict_val

array([3, 5, 1, ..., 2, 6, 6])

In [114]:
acc_cnn = accuracy_score(y_test.values, predict_val)
acc_cnn

0.9577777777777777

In [116]:
cnn2 = Sequential()

#----------------- fase de convolución -----------------
cnn2.add(Dropout(0.2, input_shape=(28, 28, 1)))

#primera capa de convoluciones
cnn2.add(Conv2D(filters=32, kernel_size=(3,3), activation='relu', kernel_initializer='uniform'))

#capa de Max-Pooling
cnn2.add(MaxPool2D(pool_size=(2,2)))

cnn2.add(Dropout(0.2))
#primera capa de convoluciones
cnn2.add(Conv2D(filters=64, kernel_size=(3,3), activation='relu', kernel_initializer='uniform'))

# segunda capa de Max-Pooling
cnn2.add(MaxPool2D(pool_size=(2,2)))

cnn2.add(Dropout(0.2))
#segunda capa de convoluciones
cnn2.add(Conv2D(filters=128, kernel_size=(3,3), activation='relu', kernel_initializer='uniform'))

#capa de Max-Pooling
cnn2.add(MaxPool2D(pool_size=(2,2)))


#capa flatten
cnn2.add(Flatten())

#----------------- fase de prediccion -----------------

cnn2.add(Dropout(0.2))
#primera capa oculta.
cnn2.add(Dense(units=128, activation='relu', kernel_initializer=initializers.GlorotUniform()))

#capa de salida
cnn2.add(Dense(units=10, activation='softmax', kernel_initializer=initializers.GlorotUniform()))

In [117]:
cnn2.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [118]:
cnn2.fit(X_train_cnn, y_train, epochs=10, batch_size=64)

Epoch 1/10
460/460 [==============================] - 29s 62ms/step - loss: 0.5246 - accuracy: 0.8334
Epoch 2/10
460/460 [==============================] - 29s 63ms/step - loss: 0.1867 - accuracy: 0.9436
Epoch 3/10
460/460 [==============================] - 28s 62ms/step - loss: 0.1407 - accuracy: 0.9564
Epoch 4/10
460/460 [==============================] - 29s 62ms/step - loss: 0.1186 - accuracy: 0.9638
Epoch 5/10
460/460 [==============================] - 29s 64ms/step - loss: 0.1047 - accuracy: 0.9674
Epoch 6/10
460/460 [==============================] - 29s 62ms/step - loss: 0.1003 - accuracy: 0.9682
Epoch 7/10
460/460 [==============================] - 28s 60ms/step - loss: 0.0847 - accuracy: 0.9745
Epoch 8/10
460/460 [==============================] - 28s 61ms/step - loss: 0.0788 - accuracy: 0.9750
Epoch 9/10
460/460 [==============================] - 28s 61ms/step - loss: 0.0772 - accuracy: 0.9749
Epoch 10/10
460/460 [==============================] - 28s 61ms/step - loss: 0.068

In [124]:
cnn2.save('/content/drive/MyDrive/Cursos/Data Science/Ciclo3/Text Mining and Image Processing/Lab2/cnn2.h5')

In [125]:
predicts = cnn2.predict(X_test_cnn)

In [126]:
predict_val = np.argmax(predicts, axis=1)
predict_val

array([3, 5, 1, ..., 2, 6, 6])

In [127]:
acc_2 = accuracy_score(y_test.values, predict_val)
acc_2

0.9217460317460318

In [123]:
pd.DataFrame({"Model": ["ANN", "CNN", "CNN2"], "Acurracy": [ac_ann, acc_cnn, acc_2]})

Model  Acurracy
0   ANN  0.879762
1   CNN  0.957778
2  CNN2  0.921746

Los Modelos Convolucionales tienen mejores resultados en el set de pruebas que los modelos ANN. Ademas se le aplico un Dropout al modelo CNN2 para reducir el sobreajuste, aunque pareciera que en el set de pruebas tambien reduce su metrica de exactitud.  